//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College_Social_Network_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        [Display(Name = "Admin ID")]
        public string Aid { get; set; }
        [Required]
        [Display(Name = "Admin Email")]
        public string Aemail { get; set; }
        [Required]
        [Display(Name = "Admin Gender")]
        public string Agender { get; set; }
        [Required]
        [Display(Name = "Admin Address")]
        public string Aaddress { get; set; }
        public Nullable<int> course_id { get; set; }
        public string RoleId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual AspNetUserRole AspNetUserRole { get; set; }
    }
}
