//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College_Social_Network_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Annnouncement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Annnouncement()
        {
            this.Course_Ann = new HashSet<Course_Ann>();
        }

        [Display(Name = "Announcement ID")]
        public int Announce_id { get; set; }
        [Required]
        [Display(Name = "Announcement Content")]
        public string Announce_content { get; set; }
        [Required]
        [Display(Name = "Announcement Time")]
        public Nullable<System.DateTime> Announce_DateTime { get; set; }
        public string Announce_FK_INS { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Ann> Course_Ann { get; set; }
    }
}
