//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College_Social_Network_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Dquestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dquestion()
        {
            this.Dreplays = new HashSet<Dreplay>();
        }

        [Display(Name = "Question ID")]
        public int Dquestion_id { get; set; }
        [Required]
        [Display(Name = "Question Content")]
        public string Dquestion_content { get; set; }
        [Required]
        [Display(Name = "Question Time")]
        public Nullable<System.DateTime> Dquestion_DateTime { get; set; }
        public string Dquestion_FK_User { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dreplay> Dreplays { get; set; }
    }
}
