//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College_Social_Network_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Dreplay
    {
        [Display(Name = "Reply ID")]
        public int Dreplay_id { get; set; }
        
        [Display(Name = "Reply Time")]
        public Nullable<System.DateTime> Dreplay_DateTime { get; set; }
        public string Dreplay_FK_User { get; set; }
        public Nullable<int> Dreplay_FK_Dquestion { get; set; }
        public string Dreplay_content { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Dquestion Dquestion { get; set; }
    }
}
