//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College_Social_Network_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Instructor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instructor()
        {
            this.tbl_categroy = new HashSet<tbl_categroy>();
            this.Annnouncements = new HashSet<Annnouncement>();
        }

        [Display(Name = "Instructor ID")]
        public string Iid { get; set; }
        [Required]
        [Display(Name = "Instructor Address")]
        public string Iaddress { get; set; }
        [Required]
        [Display(Name = "Instructor Email")]
        public string Iemail { get; set; }
        [Required]
        [Display(Name = "Instructor Gender")]
        public string Igender { get; set; }
        [Required]
        [Display(Name = "Instructor Office Hours")]
        public string Iofficehours { get; set; }
        public Nullable<int> course_id { get; set; }
        public string con_id { get; set; }
        public string RoleId { get; set; }
    
        public virtual AspNetUserRole AspNetUserRole { get; set; }
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_categroy> tbl_categroy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Annnouncement> Annnouncements { get; set; }
    }
}
