//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College_Social_Network_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.TBL_SETEXAM = new HashSet<TBL_SETEXAM>();
        }

        [Display(Name = "Student ID")]
        public string Sid { get; set; }
        [Required]
        [Display(Name = "Student Address")]
        public string Saddress { get; set; }
        [Required]
        [Display(Name = "Student Email")]
        public string Semail { get; set; }
        [Required]
        [Display(Name = "Student Gender")]
        public string Sgender { get; set; }
        [Required]
        [Display(Name = "Student Academic Year")]
        public string Sacademicyear { get; set; }
        public Nullable<int> course_id { get; set; }
        public string con_id { get; set; }
        public string RoleId { get; set; }
    
        public virtual AspNetUserRole AspNetUserRole { get; set; }
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SETEXAM> TBL_SETEXAM { get; set; }
    }
}
