//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College_Social_Network_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_QUESTIONS
    {
        [Display(Name = "Question ID")]
        public int QUESTION_ID { get; set; }
        [Required]
        [Display(Name = "Question Content")]
        public string Q_TEXT { get; set; }
        [Required]
        [Display(Name = "Option A")]
        public string OPA { get; set; }
        [Required]
        [Display(Name = "Option B")]
        public string OPB { get; set; }
        [Required]
        [Display(Name = "Option C")]
        public string OPC { get; set; }
        [Required]
        [Display(Name = "Option D")]
        public string OPD { get; set; }
        [Required]
        [Display(Name = "Correct Option")]
        public string COP { get; set; }
        public Nullable<int> q_fk_catid { get; set; }
        [Required]
        [Display(Name = "Mark")]
        public Nullable<int> Mark { get; set; }
    
        public virtual tbl_categroy tbl_categroy { get; set; }
    }
}
