//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College_Social_Network_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_categroy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_categroy()
        {
            this.TBL_QUESTIONS = new HashSet<TBL_QUESTIONS>();
            this.TBL_SETEXAM = new HashSet<TBL_SETEXAM>();
            this.Course_Cat = new HashSet<Course_Cat>();
        }

        [Display(Name = "Quiz Room ID")]
        public int cat_id { get; set; }
        [Required]
        [Display(Name = "Quiz Room Name")]
        public string cat_name { get; set; }
        public string cat_fk_adid { get; set; }
       
        [Display(Name = "Quiz Room Code")]
        public string cat_encyptedstring { get; set; }
        [Required]
        [Display(Name = "Quiz Room Time")]
        public Nullable<int> cat_time { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_QUESTIONS> TBL_QUESTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SETEXAM> TBL_SETEXAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Cat> Course_Cat { get; set; }
    }
}
