//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College_Social_Network_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_SETEXAM
    {
        [Display(Name = "Quiz ID")]
        public int EXAM_ID { get; set; }
        
        [Display(Name = "Quiz Date")]
        public Nullable<System.DateTime> EXAM_DATE { get; set; }
        public string EXAM_FK_STU { get; set; }
       
        [Display(Name = "Quiz Name")]
        public string EXAM_NAME { get; set; }
        
        [Display(Name = "Quiz Score")]
        public Nullable<int> EXAM_STD_SCORE { get; set; }
        public Nullable<int> EXAM_FK_CATID { get; set; }
        [Display(Name = "Quiz Full Mark")]
        public Nullable<int> EXAM_FullMark { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual tbl_categroy tbl_categroy { get; set; }
    }
}
